# Generated by Django 4.1.3 on 2022-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_advocate_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
