# Generated by Django 4.1.3 on 2022-11-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
