# Generated by Django 4.1.3 on 2022-11-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_advocate_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advocate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name_plural': 'companies'},
        ),
    ]
