# Generated by Django 4.1.3 on 2022-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_advocate_options_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
